name: Release

on:
  push:
    branches:
      - master
  pull_request_target:
    types:
      - closed
    branches:
      - master

jobs:
  ktlint-check:
    name: ðŸ” Ktlint Check
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Analysis static code
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck

  detekt-check:
    name: ðŸ” Detekt Check
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Analysis static code
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt

  unit-tests:
    name: ðŸ§ª Execute Unit Tests
    if: github.event.pull_request.merged == true
    needs:
      - ktlint-check
      - detekt-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Execute unit tests for domain module
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :core:domain:test

  compile:
    name: ðŸ”¨ Compile
    if: github.event.pull_request.merged == true
    needs:
      - unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Restore keystore.jks
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        run: echo $KEYSTORE_FILE | base64 -d > app/keystore.jks

      - name: Build with gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: |
            assembleProductionRelease
            -PKEYSTORE_FILE=keystore.jks
            -PKEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
            -PSIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}
            -PSIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}