name: Validate

on:
  pull_request:
    branches:
      - master

jobs:
  ktlint-check:
    name: ğŸ” Ktlint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Analysis static code
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck

  detekt-check:
    name: ğŸ” Detekt Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Analysis static code
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt

  unit-tests:
    name: ğŸ§ª Execute Unit Tests
    needs:
      - ktlint-check
      - detekt-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Execute unit tests for domain module
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :core:domain:test

  build:
    name: ğŸ”¨ Compile
    needs:
      - unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: assembleProductionRelease