name: Validate

on:
  pull_request:
    branches:
      - master

jobs:
  ktlint-check:
    name: ğŸ” Ktlint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Analysis static code
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck

  detekt-check:
    name: ğŸ” Detekt Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Analysis static code
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt

  unit-tests:
    name: ğŸ§ª Execute Unit Tests
    needs:
      - ktlint-check
      - detekt-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Execute unit tests for domain module
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :core:domain:test :core:data:test